/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model.glb -o Model.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.003}>
        <mesh geometry={nodes.Object004_1.geometry} material={materials.Bottle} position={[3019.821, 1.317, -128.163]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object005_1.geometry} material={materials.Shower} position={[2884.33, 1.317, -101.705]} rotation={[-Math.PI / 2, 0, 0]} scale={0.119} />
        <mesh geometry={nodes.Label_1.geometry} material={materials.Label} position={[3019.821, 27.957, -128.163]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/model.glb')
